language: python
python:
  - "3.5"
  - "3.6"
  - "3.7"
  - "3.8"
install:
  - pip3 install jupyter numpy scipy astropy healpy matplotlib progressbar seaborn pytest nbval
  - pip3 install .
script:
  - python3 tests/alltests.py
  - cd ${TRAVIS_BUILD_DIR}/tutorials pytest --nbval-lax
